openapi: 3.1.0
info:
  title: Deklutter API
  description: AI-powered digital decluttering assistant. Clean Gmail inbox by automatically identifying and removing spam, newsletters, and promotional emails. More providers (Yahoo, Outlook, Drive, Dropbox) coming soon!
  version: 1.0.0
  contact:
    name: Deklutter Support
    email: mohammad.illiyaz@gmail.com

servers:
  - url: https://deklutter-api.onrender.com
    description: Production server

paths:
  /gmail/scan:
    post:
      operationId: scanGmail
      summary: Scan Gmail inbox for unwanted emails
      description: Analyzes the user's Gmail inbox and classifies emails into categories (delete, review, keep). Returns statistics and email IDs for each category. User must have completed OAuth authorization first.
      security:
        - DeklutterOAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                days_back:
                  type: integer
                  description: Number of days to look back in inbox history
                  default: 30
                  minimum: 1
                  maximum: 365
                  example: 30
                limit:
                  type: integer
                  description: Maximum number of emails to scan
                  default: 100
                  minimum: 1
                  maximum: 1000
                  example: 100
      responses:
        '200':
          description: Scan completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: object
                    properties:
                      total_items:
                        type: integer
                        description: Total number of emails scanned
                        example: 127
                      counts:
                        type: object
                        properties:
                          delete:
                            type: integer
                            description: Number of emails safe to delete (spam/promotional)
                            example: 45
                          review:
                            type: integer
                            description: Number of emails that need review (uncertain)
                            example: 12
                          keep:
                            type: integer
                            description: Number of important emails to keep
                            example: 70
                      approx_size_mb:
                        type: number
                        format: float
                        description: Approximate size in MB that can be freed
                        example: 3.2
                  safe_to_delete:
                    type: array
                    description: Email IDs that are safe to delete
                    items:
                      type: string
                    example: ["msg_id_1", "msg_id_2"]
                  review:
                    type: array
                    description: Email IDs that need user review
                    items:
                      type: string
                    example: ["msg_id_3"]
                  keep:
                    type: array
                    description: Email IDs to keep
                    items:
                      type: string
                    example: ["msg_id_4", "msg_id_5"]
                  samples:
                    type: object
                    description: Sample emails from each category for user preview
                    properties:
                      delete:
                        type: array
                        description: Sample emails marked for deletion (up to 5)
                        items:
                          type: object
                          properties:
                            from:
                              type: string
                              example: "newsletter@example.com"
                            subject:
                              type: string
                              example: "Weekly deals and promotions"
                            date:
                              type: string
                              example: "Mon, 18 Oct 2025 10:30:00 +0000"
                            size_kb:
                              type: number
                              example: 45.2
                      review:
                        type: array
                        description: Sample emails for user review (up to 3)
                        items:
                          type: object
                          properties:
                            from:
                              type: string
                            subject:
                              type: string
                            date:
                              type: string
                            size_kb:
                              type: number
                      keep:
                        type: array
                        description: Sample emails to keep (up to 3)
                        items:
                          type: object
                          properties:
                            from:
                              type: string
                            subject:
                              type: string
                            date:
                              type: string
                            size_kb:
                              type: number
        '403':
          description: Gmail not authorized - User needs to complete OAuth flow first
        '500':
          description: Scan failed

  /oauth/revoke:
    post:
      operationId: revokeAccess
      summary: Revoke Gmail access and delete all user data
      description: Completely removes Deklutter's access to user's Gmail. Deletes all stored tokens and data. User can re-authorize later if needed.
      security:
        - DeklutterOAuth: []
      responses:
        '200':
          description: Access revoked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Access revoked successfully. All data deleted."
                  revoked_at:
                    type: string
                    format: date-time
                    example: "2025-10-18T12:47:00Z"
        '401':
          description: Unauthorized - Invalid token
        '500':
          description: Revoke failed

  /gmail/apply:
    post:
      operationId: applyCleanup
      summary: Apply cleanup actions to Gmail
      description: Moves specified emails to trash or applies labels. Emails moved to trash can be recovered for 30 days. User must have completed OAuth authorization first.
      security:
        - DeklutterOAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message_ids
              properties:
                message_ids:
                  type: array
                  description: List of email IDs to process
                  items:
                    type: string
                  example: ["msg_id_1", "msg_id_2", "msg_id_3"]
                mode:
                  type: string
                  description: Action to perform on emails
                  enum: [trash, label_only]
                  default: trash
                  example: trash
      responses:
        '200':
          description: Cleanup applied successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  processed:
                    type: integer
                    description: Number of emails processed
                    example: 45
                  mode:
                    type: string
                    description: Action that was performed
                    example: trash
        '403':
          description: Gmail not authorized - User needs to complete OAuth flow first
        '500':
          description: Action failed

components:
  schemas: {}
  
  securitySchemes:
    DeklutterOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://deklutter-api.onrender.com/auth/gpt/oauth/authorize
          tokenUrl: https://deklutter-api.onrender.com/auth/gpt/oauth/token
          scopes: {}
      description: OAuth 2.0 authorization for accessing user's Gmail through Deklutter
