services:
  # Web Service (FastAPI)
  - type: web
    name: deklutter-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn services.gateway.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DATABASE_URL
        fromDatabase:
          name: deklutter-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: APP_SECRET
        generateValue: true

databases:
  # PostgreSQL Database (Free Tier)
  - name: deklutter-db
    databaseName: deklutter
    user: deklutter_user
    plan: free
